[versions]
kotest = "6.1.2"

[plugins]
kover = { id = "org.jetbrains.kotlinx.kover", version = "0.9.4" }
sonar = { id = "org.sonarqube", version = "7.2.2.6593" }

[libraries]
kotest = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
